In [1]:
import pandas as pd
import numpy as np

# Load cleaned dataset
df = pd.read_csv("../data/processed/creditcard_clean.csv")

print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 Rows:")
display(df.head())

print("\nData Types:")
print(df.dtypes)

Dataset Shape: (283726, 31)

Columns:
['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount', 'Class']

First 5 Rows:

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

Data Types:
Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [2]:
df["Hour"] = (df["Time"] / 3600) % 24

def get_time_period(hour):
    if 6 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 18:
        return "Afternoon"
    elif 18 <= hour < 24:
        return "Evening"
    else:
        return "Night"

df["Time_Period"] = df["Hour"].apply(get_time_period)

print("New Time Features:")
display(df[["Time", "Hour", "Time_Period", "Class"]].head(10))

print("\nTime Period Distribution:")
print(df["Time_Period"].value_counts())

print("\nFraud by Time Period:")
print(
    pd.crosstab(
        df["Time_Period"],
        df["Class"],
        normalize="index"
    ).round(4) * 100
)

New Time Features:

   Time      Hour Time_Period  Class
0   0.0  0.000000       Night      0
1   0.0  0.000000       Night      0
2   1.0  0.000278       Night      0
3   1.0  0.000278       Night      0
4   2.0  0.000556       Night      0
5   2.0  0.000556       Night      0
6   4.0  0.001111       Night      0
7   7.0  0.001944       Night      0
8   7.0  0.001944       Night      0
9   9.0  0.002500       Night      0

Time Period Distribution:
Time_Period
Afternoon    96121
Evening      93120
Morning      70643
Night        23842
Name: count, dtype: int64

Fraud by Time Period:
Class            0     1
Time_Period
Afternoon    99.86  0.14
Evening      99.89  0.11
Morning      99.83  0.17
Night        99.52  0.48

In [3]:
print("Original Amount Statistics:")
display(df["Amount"].describe())

print("\nOriginal Amount Skewness:")
print(round(df["Amount"].skew(), 4))

df["Log_Amount"] = np.log1p(df["Amount"])

print("\nAmount Feature Comparison:")
display(
    df[["Amount", "Log_Amount", "Class"]].describe()
)

print("\nLog Amount Skewness:")
print(round(df["Log_Amount"].skew(), 4))

print("\nSample Amount Transformation:")
display(
    df[["Amount", "Log_Amount", "Class"]].head(10)
)

Original Amount Statistics:

count    283726.000000
mean         88.472687
std         250.399437
min           0.000000
25%           5.600000
50%          22.000000
75%          77.510000
max       25691.160000
Name: Amount, dtype: float64

Original Amount Skewness:
16.9788

Amount Feature Comparison:

              Amount     Log_Amount          Class
count  283726.000000  283726.000000  283726.000000
mean       88.472687       3.153760       0.001667
std       250.399437       1.657080       0.040796
min         0.000000       0.000000       0.000000
25%         5.600000       1.887070       0.000000
50%        22.000000       3.135494       0.000000
75%        77.510000       4.363226       0.000000
max     25691.160000      10.153941       1.000000

Log Amount Skewness:
0.1614

Sample Amount Transformation:

   Amount  Log_Amount  Class
0  149.62    5.014760      0
1    2.69    1.305626      0
2  378.66    5.939276      0
3  123.50    4.824306      0
4   69.99    4.262539      0
5    3.67    1.541159      0
6    4.99    1.790091      0
7   40.80    3.732896      0
8   93.20    4.545420      0
9    3.68    1.543298      0

In [4]:
print("Dataset Shape After Feature Engineering:")
print(df.shape)

print("\nAll Columns:")
print(df.columns.tolist())

new_features = ["Hour", "Time_Period", "Log_Amount"]

print("\nNew Features:")
display(df[new_features].head())

print("\nMissing Values:")
print(df.isnull().sum().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nUnique Time Periods:")
print(df["Time_Period"].unique())

print("\nHour Range:")
print(df["Hour"].min(), "to", df["Hour"].max())

numeric_features = df.select_dtypes(include=np.number)

correlation_with_class = (
    numeric_features.corr()["Class"]
    .drop("Class")
    .sort_values(key=abs, ascending=False)
)

print("\nTop Numeric Features Correlated with Class:")
display(correlation_with_class.head(15))

print("\nFinal Feature Engineering Validation:")

if df.isnull().sum().sum() == 0:
    print("✓ No missing values")

if df.duplicated().sum() == 0:
    print("✓ No duplicate rows")

if df["Hour"].between(0, 24, inclusive="left").all():
    print("✓ Hour feature is valid")

if (df["Log_Amount"] >= 0).all():
    print("✓ Log_Amount feature is valid")

print("\nFeature engineering validation completed!")

Dataset Shape After Feature Engineering:
(283726, 34)

All Columns:
['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount', 'Class', 'Hour', 'Time_Period', 'Log_Amount']

New Features:

       Hour Time_Period  Log_Amount
0  0.000000       Night    5.014760
1  0.000000       Night    1.305626
2  0.000278       Night    5.939276
3  0.000278       Night    4.824306
4  0.000556       Night    4.262539

Missing Values:
0

Duplicate Rows:
0

Unique Time Periods:
<StringArray>
['Night', 'Morning', 'Afternoon', 'Evening']
Length: 4, dtype: str

Hour Range:
0.0 to 23.999444444444446

Top Numeric Features Correlated with Class:

V17   -0.313498
V14   -0.293375
V12   -0.250711
V10   -0.206971
V16   -0.187186
V3    -0.182322
V7    -0.172347
V11    0.149067
V4     0.129326
V18   -0.105340
V1    -0.094486
V9    -0.094021
V5    -0.087812
V2     0.084624
V6    -0.043915
Name: Class, dtype: float64

Final Feature Engineering Validation:
✓ No missing values
✓ No duplicate rows
✓ Hour feature is valid
✓ Log_Amount feature is valid

Feature engineering validation completed!

In [5]:
output_path = "../data/processed/creditcard_feature_engineered.csv"

df.to_csv(output_path, index=False)

print("Feature-engineered dataset saved successfully!")
print("File:", output_path)
print("Final Shape:", df.shape)

# Verify saved file
saved_df = pd.read_csv(output_path)

print("\nVerification:")
print("Saved Shape:", saved_df.shape)
print("Missing Values:", saved_df.isnull().sum().sum())
print("Duplicate Rows:", saved_df.duplicated().sum())

Feature-engineered dataset saved successfully!
File: creditcard_feature_engineered.csv
Final Shape: (283726, 34)

Verification:
Saved Shape: (283726, 34)
Missing Values: 0
Duplicate Rows: 0